// Donnees extraites du studio Reaper — valise tablette
const SUBS = [
  // ============ ACTE I — texte EXACT de chaque page (base : traductions d'avril, adaptées au Baron) ============
  {a:6,  b:6,  it:'E goder voi potrete?', fr:'Et vous pourrez en profiter ?', jeu:'La fête commence chez Violetta — tu entres avec Flora.'},
  {a:7,  b:7,  it:'Sì, la vita s’addoppia al gioir.', fr:'Oui, la vie se double par le plaisir.', jeu:'TA portée BARONE — pas celle du Marquis plus bas.'},
  {a:8,  b:9,  it:'(suite de l’ensemble d’introduction)', fr:'(suite de l’ensemble)', jeu:''},
  {a:10, b:10, it:'« Caro Alfredo! » (Marchese)', fr:'« Cher Alfredo ! » — c’est le MARQUIS qui chante', jeu:'🔇 Toi, silence : c’était ta ligne à Nice, plus maintenant.'},
  {a:11, b:11, it:'Ben diceste… le cure segrete fuga sempre l’amico licor.', fr:'Bien dit… les soucis secrets, l’ami alcool les chasse toujours.', jeu:''},
  {a:12, b:13, it:'È al convito che s’apre ogni cor.', fr:'C’est au banquet que s’ouvre chaque cœur.', jeu:'Bar. + Dot. + Marc. sur la même portée — du connu.'},
  {a:14, b:14, it:'Vi conosco da un anno soltanto.', fr:'Je ne vous connais que depuis un an.', jeu:'Réponse piquée à Violetta — possessif, un peu vexé.'},
  {a:15, b:15, it:'M’è increscioso quel giovin…', fr:'Ce jeune homme me déplaît…', jeu:'⚠️ Bas, à Flora — le Marquis, lui, chantait « È a madama » : plus toi !'},
  {a:16, b:16, it:'Beviamo.', fr:'Buvons.', jeu:''},
  {a:17, b:17, it:'…viamo, beviam.', fr:'…buvons, buvons.', jeu:''},
  {a:18, b:18, it:'Sì, sì, un brindisi. (gli altri)', fr:'« Oui, oui, un toast ! » (les autres)', jeu:'🔇 TOI : (Il Barone accenna che no) — tu REFUSES de la tête, hautain.'},
  {a:19, b:19, it:'Sì, attenti al cantor.', fr:'Oui, écoutons le chanteur.', jeu:'⚠️ « Sì » — pas « Dunque attenti » du Marquis !'},
  {a:20, b:21, it:'(Alfredo) Libiamo ne’ lieti calici…', fr:'Couplet d’Alfredo — buvons dans les coupes joyeuses', jeu:'Tu écoutes — il brille devant TA maîtresse.'},
  {a:22, b:23, it:'Ah! libiam, amor fra i calici più caldi baci avrà.', fr:'Ah ! buvons : l’amour, parmi les coupes, aura des baisers plus ardents.', jeu:'Refrain à tous — identique à Nice.'},
  {a:24, b:24, it:'(Violetta) Tra voi saprò dividere…', fr:'Couplet de Violetta', jeu:'Tu écoutes, regard sur elle.'},
  {a:25, b:27, it:'Ah! godiamo, la tazza e il cantico la notte abbella e il riso…', fr:'Ah ! jouissons : la coupe et le chant embellissent la nuit et le rire…', jeu:''},
  {a:28, b:28, it:'Ah sì, godiamo la tazza e il cantico…', fr:'Ah oui, jouissons de la coupe et du chant…', jeu:''},
  {a:29, b:31, it:'…in questo paradiso ne scopra il nuovo dì.', fr:'…dans ce paradis, que le jour nouveau nous surprenne.', jeu:''},
  {a:32, b:32, it:'…ne scopra il nuovo dì.', fr:'…que le jour nouveau nous surprenne.', jeu:'⚠️ FIN du Brindisi : ta ligne diffère un peu du Marquis ici — vérifie tes notes.'},
  {a:33, b:33, it:'Che è ciò?', fr:'Qu’est-ce donc ?', jeu:'Violetta chancelle — début du malaise.'},
  {a:34, b:34, it:'Oh, il gentil pensier! Tutti accettiamo.', fr:'Oh, la charmante idée ! Nous acceptons tous.', jeu:''},
  {a:35, b:35, it:'Che avete?', fr:'Qu’avez-vous ?', jeu:''},
  {a:36, b:36, it:'Che mai v’arresta?', fr:'Qu’est-ce qui vous arrête ?', jeu:''},
  {a:37, b:37, it:'Ancora! Oh ciel! ch’è questo?', fr:'Encore ! Oh ciel ! qu’y a-t-il ?', jeu:'Inquiétude réelle mais réservée — tu n’accours pas comme Alfredo.'},
  {a:38, b:38, it:'Come bramate.', fr:'Comme vous voudrez. [SORTIE]', jeu:'Vous passez au salon de danse — fin de la section piano 3.'},
  {a:39, b:51, it:'(Violetta sola: Ah, fors’è lui… Sempre libera)', fr:'Grande scène de Violetta seule — tu n’y es pas', jeu:'Repos en coulisse.'},
  {a:52, b:52, it:'Si ridesta in ciel l’aurora, e n’è forza ripartir…', fr:'L’aurore se réveille au ciel, il faut repartir…', jeu:'Stretta — les invités prennent congé.'},
  {a:53, b:53, it:'La città di feste è piena, volge il tempo dei piacer…', fr:'La ville est pleine de fêtes, c’est le temps des plaisirs…', jeu:''},
  {a:54, b:56, it:'…mercè a voi, gentil signora, di sì splendido gioir.', fr:'…merci à vous, gentille dame, pour ce splendide plaisir.', jeu:''},
  {a:57, b:57, it:'La città di feste è piena…', fr:'La ville est pleine de fêtes…', jeu:''},
  {a:58, b:58, it:'…nel riposo ancor la lena si ritempri per goder.', fr:'…que dans le repos nos forces se retrempent pour jouir.', jeu:''},
  {a:59, b:63, it:'Si ridesta… mercè a voi… la città di feste…', fr:'L’aurore se réveille… merci à vous… la ville en fête…', jeu:''},
  {a:64, b:64, it:'(dernière page)', fr:'FIN DE L’ACTE I — sortie générale', jeu:''},
  // ============ ACTE II sc.2 — chez Flora ============
  {a:139, b:139, it:'(Marchese) La novità ignorate? Violetta e Germont sono disgiunti. Ella verrà qui col Barone.', fr:'« Vous savez la nouvelle ? Violetta et Germont sont séparés. Elle viendra ici avec le Baron. »', jeu:'Le Marquis annonce TON arrivée — on parle de toi avant que tu entres.'},
  {a:140, b:142, it:'Giungono gli amici.', fr:'Les amis arrivent.', jeu:''},
  {a:143, b:144, it:'(Marchese) Che diancin vi pensate? L’accusa è falsità!', fr:'« Que diable pensez-vous ? L’accusation est fausse ! »', jeu:''},
  {a:145, b:147, it:'Su via, si stenda un velo sui fatti del passato; già quel ch’è stato è stato, badiamo all’avvenir.', fr:'Allons, tirons un voile sur le passé ; ce qui est fait est fait, pensons à l’avenir.', jeu:''},
  {a:148, b:152, it:'(Zingarelle) Noi siamo zingarelle…', fr:'Chœur des bohémiennes (les « Carmen »)', jeu:'🔇 Tu n’y es plus — tu entrais ici en Marquis.'},
  {a:153, b:159, it:'(Mattadori) È Piquillo un bel gagliardo…', fr:'Chœur des toréadors', jeu:'🔇 Tu n’y es plus.'},
  {a:160, b:160, it:'Alfredo!… Voi!…', fr:'Alfredo !… Vous !…', jeu:'Alfredo paraît — surprise générale.'},
  {a:161, b:161, it:'Ben disinvolto!… Bravo!', fr:'Bien désinvolte !… Bravo !', jeu:''},
  {a:162, b:162, it:'…via, giuocar si può. (Entra Violetta a braccio del Barone)', fr:'« …allons, on peut jouer. » — VIOLETTA ENTRE À TON BRAS', jeu:'TON ENTRÉE : tu crois avoir gagné — elle est revenue à toi.'},
  {a:163, b:163,
   it:'(Flora) Qui desiata giungi — (Viol.) Cessi al cortese invito — (Flora) Grata vi son, barone, d’averlo pur gradito — <span class="bar">TOI (piano a Violetta) : Germont è qui! il vedete?</span> — (Viol.) (Cielo! gli è vero!)… Il vedo.',
   fr:'« Te voilà, on t’attendait ! » — « J’ai cédé à l’aimable invitation. » — « Merci, Baron, d’avoir accepté aussi. » — <span class="bar">« GERMONT [= ALFREDO !] EST ICI ! LE VOYEZ-VOUS ? »</span> — « (Ciel ! c’est vrai !)… Je le vois. »',
   jeu:'Ton entrée, Violetta au bras. Tu repères ton rival à la seconde. (« Germont » = le nom de famille d’Alfredo !)'},
  {a:164, b:164,
   it:'<span class="bar">TOI (cupo) : Da voi non un sol detto si volga a questo Alfredo… non un detto!</span> — (Viol.) (Ah, perchè venni, incauta! Pietà, gran Dio, di me!) — (Flora) Meco t’assidi ; narrami : quai novità vegg’io?',
   fr:'<span class="bar">« Que pas un seul mot de vous n’aille à cet Alfredo… PAS UN MOT ! »</span> — « (Pourquoi suis-je venue, imprudente ! Pitié, grand Dieu !) » — Flora : « Assieds-toi près de moi, raconte… »',
   jeu:'Ordre murmuré, mâchoire serrée. 📜 Puis : Violetta au divan avec Flora et le Docteur ; TOI à l’écart AVEC LE MARQUIS.'},
  {a:165, b:165,
   it:'(Alf.) Un quattro! — (Gast.) Ancora hai vinto — (Alf.) Sfortuna nell’amore fortuna reca al giuoco… — (tutti) È sempre vincitore!.. — (Alf.) Oh vincerò stassera ; e l’oro guadagnato poscia a goder tra’ campi ritornerò beato.',
   fr:'« Un quatre ! » — « Tu as encore gagné. » — « Malheur en amour, bonheur au jeu… » — « Il gagne à tous les coups ! » — « Je vais gagner ce soir, et avec l’or gagné je retournerai heureux à la campagne. »',
   jeu:'La pique « malheur en amour » est POUR TOI, devant tout le salon. Tu observes de loin, masque impassible.'},
  {a:166, b:166,
   it:'(Flora) Solo? — (Alf.) No… con tale che vi fu meco ancora, poi mi sfuggia — (Viol.) Mio Dio! (Frenatevi, o vi lascio) — (Gast.) Pietà di lei — <span class="bar">TOI : Signor!</span> — (Alf.) Barone, m’appellaste? — <span class="bar">TOI : Siete in sì gran fortuna, che al…</span>',
   fr:'« Seul ? » — « Non… avec celle qui m’a fui » — « Mon Dieu ! (Retenez-vous ou je vous quitte) » — « Aie pitié d’elle » — <span class="bar">« MONSIEUR ! »</span> — « Baron, vous m’avez appelé ? » — <span class="bar">« Vous êtes en telle veine que… (suite p.167) »</span>',
   jeu:'🔥 Ton éclat (con mal frenata ira) : Alfredo vient d’annoncer qu’il reprendra Violetta. Ta phrase se coupe en bas de page — elle finit p.167.'},
  {a:167, b:167,
   it:'<span class="bar">TOI : …giuoco mi tentaste</span> — (Alf., ironico) Sì?.. La disfida accetto — (Viol.) Che fia?.. morir mi sento!.. pietà, gran Dio, di me! — <span class="bar">TOI (punta) : Cento luigi a destra…</span> — (Alf.) Ed alla manca cento…',
   fr:'<span class="bar">« …vous me tentez au jeu. »</span> — « Oui ?.. J’accepte le défi. » — « Que va-t-il arriver ?.. je me sens mourir !.. pitié, grand Dieu ! » — <span class="bar">« CENT LOUIS À DROITE… »</span> — « Et cent à gauche… »',
   jeu:'Le duel aux cartes commence : TOI contre Alfredo, Gastone distribue. « punta » = tu mises — c’est ici que tu viens à la table.'},
  {a:168, b:168,
   it:'(Gast.) Un asso… un fante… hai vinto! — <span class="bar">TOI : Il doppio?…</span> — (Alf.) Il doppio sia — (Gast.) Un quattro… un sette… — (tutti) Ancora!.. — (Alf.) Pur la vittoria è mia!',
   fr:'« Un as… un valet… tu as gagné ! » — <span class="bar">« QUITTE OU DOUBLE ?… »</span> — « Va pour le double. » — « Un quatre… un sept… » — « Encore ! » — « La victoire est encore à moi ! »',
   jeu:'Deux donnes, deux défaites pour toi. (Ton argent perdu = celui qu’Alfredo jettera au visage de Violetta !)'},
  {a:169, b:169,
   it:'(Gast., Dott., March. e coro) Bravo davver!.. la sorte è tutta per Alfredo!.. — (Flora) Del villeggiar la spesa farà il baron, già il vedo.',
   fr:'« Bravo vraiment !.. la chance est toute pour Alfredo !.. » — Flora : « C’est le Baron qui paiera le séjour à la campagne, je le vois déjà ! »',
   jeu:'Le salon te raille — tu encaisses, droit, sans un mot.'},
  {a:170, b:170,
   it:'(Alf., al Barone) Seguite pur! — (un servo) La cena è pronta — (tutti, <span class="bar">TOI compris</span>) Andiamo, andiamo… Andiam! — (Viol., da sè) (Che fi…',
   fr:'« Continuez donc ! » — « Le souper est servi. » — <span class="bar">« ALLONS-Y, ALLONS-Y ! » (toi aussi, avec tous)</span> — Violetta : « (Que va-t-il arriver…) »',
   jeu:'📜 (tutti partono, restando indietro Alfredo ed il Barone) : tous sortent SAUF Alfredo et TOI. (Ton « Andiamo » : la pianiste l’a sauté — tu le connais déjà.)'},
  {a:171, b:171,
   it:'(Viol.) …a?.. morir mi sento!.. pietà, gran Dio, di me! — (Alf.) Se continuar v’aggrada… — <span class="bar">TOI : Per ora nol possiamo : più tardi la rivincita.</span> — (Alf.) Al giuoco che vorrete — <span class="bar">TOI : Seguiam gli amici…</span>',
   fr:'« …je me sens mourir !.. pitié, grand Dieu, pitié de moi ! » (elle prie en sortant) — « S’il vous plaît de continuer… » — <span class="bar">« Pour l’instant nous ne le pouvons pas : plus tard, LA REVANCHE. »</span> — « Au jeu que vous voudrez. » — <span class="bar">« Suivons nos amis… »</span>',
   jeu:'⚔️ Seuls, face à face. « La rivincita » = le duel, à mots couverts — vous l’avez compris tous les deux.'},
  {a:172, b:172,
   it:'<span class="bar">TOI : …poscia…</span> — (Alf.) Sarò qual bramerete. Andiam. — <span class="bar">TOI (ben lontano) : Andiam.</span> — (Viol., ritorna affannata) Invitato a qui seguirmi, verrà…',
   fr:'<span class="bar">« …ENSUITE… »</span> — « Je serai ce que vous voudrez. Allons. » — <span class="bar">« Allons. » (déjà loin — froid, presque ironique : à toi de choisir)</span> — Violetta revient, haletante : « Invité à me suivre, il va venir… »',
   jeu:'« Poscia » = « ensuite » : la fin de TA phrase « Suivons nos amis ; ENSUITE… » — la menace reste suspendue en l’air. Fin de ta partie.'},
  {a:173, b:177, it:'(Violetta e Alfredo soli)', fr:'Scène Violetta–Alfredo — tu es en coulisse', jeu:'Il lui arrache un faux aveu : « j’aime le Baron ». La bombe est amorcée.'},
  {a:178, b:178,
   it:'(tutti, <span class="bar">TOI compris</span>) Ne appellaste?.. che volete?.. — (Alf.) Questa don…',
   fr:'<span class="bar">« Vous nous avez appelés ?.. que voulez-vous ?.. »</span> — Alfredo : « Cette femme… »',
   jeu:'📜 (Tutti entrano confusamente) — le cri de Violetta fait TOUT rentrer en désordre, toi en tête. Didascalie : elle s’appuie, abattue, à la petite table.'},
  {a:179, b:179,
   it:'(Alf.) …conoscete? Che facesse non sapete? — (tutti, <span class="bar">TOI compris</span>) Chi? Violetta?… No. — (Viol.) (Ah! taci.) — (Alf.) Ogni suo aver tal femmina per amor mio sperdea…',
   fr:'« …vous la connaissez ? Savez-vous ce qu’elle a fait ? » — <span class="bar">« Qui ? Violetta ?… Non. »</span> — « (Ah ! tais-toi.) » — « Tout son bien, cette femme l’a dilapidé pour mon amour… »',
   jeu:'Alfredo prend le salon à témoin — tu réponds AVEC tous, encore incrédule.'},
  {a:180, b:180,
   it:'(Alf.) Io cieco, vile, misero, tutto accettar potea. Ma è tempo ancora!.. tergermi da tanta macchia bramo… Qui testimon vi chiamo…',
   fr:'« Moi, aveugle, vil, misérable, j’acceptais tout. Mais il est encore temps !.. je veux me laver d’une telle tache… Je vous prends ici à témoin… »',
   jeu:'La confession publique monte (Animato) — le pire arrive. Toi : tu comprends une seconde avant les autres.'},
  {a:181, b:181,
   it:'(Alf.) …che qui pagata io l’ho! 📜 (getta una borsa a’ piè di Violetta, che sviene) — (tutti, <span class="bar">TOI voix 1</span>) Oh, infamia orribile tu commettesti! un cor sensibile…',
   fr:'« …et je déclare ici L’AVOIR PAYÉE ! » — il jette la bourse aux pieds de Violetta, qui S’ÉVANOUIT dans les bras de Flora — <span class="bar">« OH, INFAMIE HORRIBLE ! »</span>',
   jeu:'⚠️ Imprimé sur la page : « BAR. e DOT. coi 1i » = TOI AVEC LES PREMIERS (voix du haut), le Marquis avec les seconds ! VELOCISSIMO.'},
  {a:182, b:182,
   it:'(tutti, <span class="bar">voix 1</span>) …così uccidesti! Di donne ignobile insultator…',
   fr:'« …tu as tué un cœur sensible ! Ignoble insulteur de femmes… »',
   jeu:'⚠️ Voix 1 toujours — l’indignation déferle.'},
  {a:183, b:184,
   it:'(tutti, <span class="bar">voix 1</span>) …di qua allontanati, ne desti orror, ne desti orror!',
   fr:'« …éloigne-toi d’ici : tu nous fais HORREUR ! » (répété jusqu’au point d’orgue)',
   jeu:'Le salon entier chasse Alfredo. Toi : la colère du groupe ET la tienne propre — elle est ta dame.'},
  {a:185, b:186, it:'(Germont padre) Di sprezzo degno sè stesso rende chi pur nell’ira la donna offende.', fr:'« Il se rend digne de mépris, celui qui même en colère offense une femme. »', jeu:'LE PÈRE vient d’entrer et foudroie son fils. Toi : silence éloquent, tu prépares ta réponse d’homme d’honneur.'},
  {a:187, b:187, it:'🔥 <span class="bar">TOI (piano, ad Alfredo) : A questa donna l’atroce insulto qui tutti offese…</span>', fr:'<span class="bar">« L’atroce insulte faite à cette femme nous a tous offensés… »</span>', jeu:'TA ligne, à voix basse, à Alfredo seul — pendant que tous chantent « Oh quanto peni ».'},
  {a:188, b:188, it:'🔥 <span class="bar">TOI : …ma non inulto fia tanto oltraggio…</span>', fr:'<span class="bar">« …mais un tel outrage ne restera pas impuni… »</span>', jeu:'Le gant est jeté — glacial.'},
  {a:189, b:189, it:'🔥 <span class="bar">TOI : …provar vi voglio che il vostro orgoglio fiaccar saprò!</span>', fr:'<span class="bar">« …je veux vous prouver que je saurai briser votre orgueil ! »</span>', jeu:'Regard planté dans le sien. Le duel est scellé.'},
  {a:190, b:190,
   it:'<span class="bar">TOI : …-prò!</span> (fin de ta phrase) — (Viol., riavvenendosi, debolissima) Alfredo, Alfredo, di questo core non puoi comprendere tutto l’amore…',
   fr:'<span class="bar">Ta DERNIÈRE note de provocation tombe ici</span> — puis Violetta, revenant à elle, à peine audible : « Alfredo, tu ne peux pas comprendre tout l’amour de ce cœur… »',
   jeu:'Tout le monde se fige : la mourante parle. Toi : immobile, la menace encore aux lèvres.'},
  {a:191, b:194, it:'(tutti) Oh, quanto peni! ma pur fa cor, qui soffre ognuno del tuo dolor…', fr:'« Oh, combien tu souffres ! Courage : chacun ici souffre de ta douleur… »', jeu:'Ta ligne propre continue dans la masse — regard sur Alfredo.'},
  {a:195, b:205, it:'(tutti) …fra cari amici qui sei soltanto, rasciuga il pianto che t’inondò.', fr:'« …tu n’es qu’entre amis chers : sèche les larmes qui t’ont inondée. »', jeu:''},
  {a:206, b:206, it:'(dernière page)', fr:'FIN — sortie vers le duel', jeu:'Regard à Alfredo jusqu’au rideau.'},
];
const TOC = [
  {h: 'ACTE I — chez Violetta'},
  {n: 'Introduction — entrée', p: 7},
  {n: '« Vi conosco da un anno »', p: 14},
  {n: 'Brindisi — Libiamo', p: 21},
  {n: 'Valzer — malaise', p: 33},
  {n: 'Stretta finale', p: 52},
  {n: 'Fin de l’Acte I', p: 64},
  {h: 'ACTE II — chez Flora'},
  {n: 'Entrée du Baron (page d’avance)', p: 162},
  {n: '« Germont è qui ! » — jalousie', p: 163},
  {n: 'Jeu de cartes — « Il doppio sia »', p: 167},
  {n: '« Ne appellaste ? »', p: 178},
  {n: 'Scandale — « Oh infamia »', p: 181},
  {n: '🔥 PROVOCATION — « A questa donna »', p: 187},
  {n: 'Final — « Oh quanto peni »', p: 190},
  {n: 'Fin du rôle', p: 206},
];
function rangeArr(a,b){const r=[];for(let i=a;i<=b;i++)r.push(i);return r}
const BARON_PAGES = [...rangeArr(6, 38), ...rangeArr(52, 64), ...rangeArr(162, 172), ...rangeArr(177, 206)];
